image: registry.gitlab.com/yakshaving.art/dockerfiles/go-builder:0.0.1
stages:
  - build
  - docker_image
  - release

build-binary:
  stage: build
  # coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/' # not a single test, forget coverage
  cache:
    paths:
    - vendor
  artifacts:
    paths:
    - nomad-exporter
  script:
    - go mod download
    - make build

.build-image: &build-image
  image: docker:stable
  stage: release
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
  after_script:
    - docker logout ${CI_REGISTRY}

build_docker:
  <<: *build-image
  script:
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
      --tag ${CI_REGISTRY_IMAGE}:latest .
  except:
  - master

release_latest:
  <<: *build-image
  script:
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
      --tag ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
  - master

release_tag:
  <<: *build-image
  script:
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
  - tags
