project_name: nomad-exporter
release:
  github:
    owner: pcarranza
    name: nomad-exporter
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X gitlab.com/yakshaving.art/nomad-exporter/version.Version={{.Version}} -X gitlab.com/yakshaving.art/nomad-exporter/version.Commit={{.Commit}} -X gitlab.com/yakshaving.art/nomad-exporter/version.Date={{.Date}}
  binary: nomad-exporter
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
changelog:
  filters:
    exclude:
      - typo
      - Fix
      - Merge
      - WIP
dockers:
  - image: pcarranza/nomad-exporter
    goos: linux
    goarch: amd64
    goarm: ''
    binary: nomad-exporter
    dockerfile: Dockerfile
    tag_templates:
      - '{{ .Tag }}'
      - latest
